((js2-mode . ((lsp-eslint-node . "yarn node")
							(lsp-eslint-node-path . ".yarn/sdks")
					    (lsp-eslint-working-directories . [(mode "auto")])
					    (lsp-eslint-package-manager . "yarn")
 			  (eval . (let ((project-directory (car (dir-locals-find-file default-directory))))
												(setq lsp-clients-typescript-prefer-use-project-ts-server t
													    lsp-clients-typescript-project-ts-server-path (concat project-directory ".yarn/sdks/typescript/bin/tsserver"))))))
 (typescript-mode . ((lsp-eslint-node . "yarn node")
									 (lsp-eslint-node-path . ".yarn/sdks")
								 (lsp-eslint-working-directories . [(mode "auto")])
								 (lsp-eslint-package-manager . "yarn")
 					 (eval . (let ((project-directory (car (dir-locals-find-file default-directory))))
													   (setq lsp-clients-typescript-prefer-use-project-ts-server t
													    lsp-clients-typescript-project-ts-server-path (concat project-directory ".yarn/sdks/typescript/bin/tsserver"))))))
 (typescript-tsx-mode . ((lsp-eslint-node . "yarn node")
										 (lsp-eslint-node-path . ".yarn/sdks")
									 (lsp-eslint-working-directories . [(mode "auto")])
									 (lsp-eslint-package-manager . "yarn")
 						 (eval . (let ((project-directory (car (dir-locals-find-file default-directory))))
														   (setq lsp-clients-typescript-prefer-use-project-ts-server t
													    lsp-clients-typescript-project-ts-server-path (concat project-directory ".yarn/sdks/typescript/bin/tsserver")))))))
